[project]
name = "tracking"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "gdown>=6.1.0",
    "numpy>=2.4.4",
    "nvidia-modelopt[onnx]>=0.44",
    "opencv-python>=4.13.0.92",
    "pyside6>=6.11.1",
    "scipy>=1.17.1",
    "setuptools>=70.2.0",
    "tensorboard>=2.20.0",
    "tensorrt>=11.1.0.106",
    "torch==2.11.0+cu128",
    "torchreid>=0.2.5",
    "torchvision==0.26.0+cu128",
    "ultralytics>=8.4.82",
    "utils>=1.0.2",
    "wheel>=0.47.0",
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu128" }
torchvision = { index = "pytorch-cu128"}